"use client";

import type { ScoredOffer } from "@/lib/score";

const PLATFORM_COLOR: Record<string, string> = {
  booking: "#4f8cff",
  agoda: "#f59cd6",
  expedia: "#6df0c2",
  trip: "#f7c45a",
};

interface Props {
  offers: ScoredOffer[];
  highlightedId: string | null;
  onHighlight: (id: string | null) => void;
  onSelect: (id: string) => void;
  selectedIds: string[];
  destination: string;
}

/**
 * Schematic SVG map. Not a real basemap — it places hotels around a synthetic
 * destination centroid (0, 0) using the lat/lng-style offsets generated by
 * the connector mocks. Concentric rings show 0.5 / 1 / 2 km distances.
 *
 * Skipping a real map dependency keeps the bundle small and the offline demo
 * working. When real coords are available, the same layout math holds —
 * project lat/lng to (x, y) relative to a chosen centre and pass them in.
 */
export function MapPanel({
  offers,
  highlightedId,
  onHighlight,
  onSelect,
  selectedIds,
  destination,
}: Props) {
  const points = offers.filter((o) => o.coords);
  if (points.length === 0) {
    return (
      <div className="map-empty">
        <p className="muted">No coordinates available for these offers.</p>
      </div>
    );
  }

  // Find the bounding distance so every hotel fits within the viewBox.
  const maxKm = Math.max(0.8, ...points.map((p) => p.distanceKm ?? 1)) * 1.2;
  const viewBox = 200;
  const half = viewBox / 2;
  const scale = half / maxKm;

  return (
    <div className="map">
      <svg viewBox={`0 0 ${viewBox} ${viewBox}`} className="map-svg" role="img" aria-label="Schematic map of hotel locations">
        <defs>
          <radialGradient id="map-bg" cx="50%" cy="50%" r="55%">
            <stop offset="0%" stopColor="rgba(79, 140, 255, 0.18)" />
            <stop offset="100%" stopColor="rgba(11, 16, 32, 0)" />
          </radialGradient>
        </defs>
        <rect x="0" y="0" width={viewBox} height={viewBox} fill="url(#map-bg)" />

        {/* Distance rings */}
        {[0.5, 1, 2].filter((km) => km <= maxKm).map((km) => (
          <circle
            key={km}
            cx={half}
            cy={half}
            r={km * scale}
            fill="none"
            stroke="rgba(147, 160, 194, 0.25)"
            strokeDasharray="2 3"
          />
        ))}

        {/* Centroid */}
        <circle cx={half} cy={half} r={3.5} fill="#e8ecf7" />
        <text x={half + 6} y={half + 3} fontSize="7" fill="#93a0c2">
          {destination} centre
        </text>

        {points.map((o) => {
          const x = half + (o.coords!.lng * 111) * scale;
          const y = half - (o.coords!.lat * 111) * scale;
          const isHi = highlightedId === o.id;
          const isSel = selectedIds.includes(o.id);
          const radius = isHi ? 7 : isSel ? 5.5 : 4;
          return (
            <g
              key={o.id}
              className="map-pin"
              onMouseEnter={() => onHighlight(o.id)}
              onMouseLeave={() => onHighlight(null)}
              onClick={() => onSelect(o.id)}
              tabIndex={0}
            >
              <circle
                cx={x}
                cy={y}
                r={radius}
                fill={PLATFORM_COLOR[o.platform] ?? "#4f8cff"}
                stroke={isSel ? "#ffffff" : "rgba(11,16,32,0.6)"}
                strokeWidth={isSel ? 1.5 : 0.8}
              />
              {isHi && (
                <g>
                  <rect
                    x={x + 8}
                    y={y - 14}
                    width={Math.min(120, o.hotelName.length * 5 + 8)}
                    height={20}
                    rx={3}
                    fill="rgba(11, 16, 32, 0.95)"
                    stroke="rgba(79, 140, 255, 0.5)"
                  />
                  <text x={x + 12} y={y - 5} fontSize="7" fill="#e8ecf7">
                    {o.hotelName.slice(0, 22)}
                  </text>
                  <text x={x + 12} y={y + 3} fontSize="6" fill="#6df0c2">
                    {o.totalPrice.currency} {Math.round(o.totalPrice.amount)} · {o.score}/100
                  </text>
                </g>
              )}
            </g>
          );
        })}
      </svg>
      <div className="map-legend">
        {Object.entries(PLATFORM_COLOR).map(([id, color]) => (
          <span key={id} className="map-legend-item">
            <span className="map-legend-swatch" style={{ background: color }} />
            {id}
          </span>
        ))}
      </div>
      <p className="map-disclaimer">
        Schematic only — positions are relative to the destination centre, not a geographic map.
      </p>
    </div>
  );
}
